# Generated by Django 6.1.1 on 2026-09-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('lesson_started', 'Leçon démarrée'), ('lesson_completed', 'Leçon terminée'), ('quiz_completed', 'Quiz terminé'), ('exercise_submitted', 'Exercice soumis'), ('ai_session_started', 'Session IA'), ('course_purchased', 'Formation achetée'), ('certificate_issued', 'Certificat délivré')], db_index=True, max_length=40)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
