# Generated by Django 6.1.1 on 2026-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'Compte créé'), ('course_enrolled', 'Formation rejointe'), ('lesson_started', 'Leçon démarrée'), ('lesson_completed', 'Leçon terminée'), ('quiz_completed', 'Quiz terminé'), ('exercise_submitted', 'Exercice soumis'), ('ai_session_started', 'Session IA'), ('course_purchased', 'Formation achetée'), ('certificate_issued', 'Certificat délivré')], db_index=True, max_length=40),
        ),
    ]
