# Generated by Django 6.1.1 on 2026-09-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontext',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_contexts', to='courses.course'),
        ),
        migrations.AddField(
            model_name='aimemory',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiagent'),
        ),
    ]
