# Generated by Django 6.1.1 on 2026-09-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='Ressources externes recommandées par ORBITE. Chaque entrée : {"titre": "...", "url": "...", "description": "...", "gratuit": true}.'),
        ),
    ]
