# Generated by Django 6.1.1 on 2026-09-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiagent_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisession',
            name='summary',
            field=models.TextField(blank=True, help_text='Résumé roulant des échanges passés (mémoire longue des sessions).'),
        ),
    ]
