# Generated by Django 6.1.1 on 2026-09-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('exercise_type', models.CharField(choices=[('text', 'Réponse textuelle'), ('strategy', 'Stratégie'), ('creative', 'Travail visuel'), ('code', 'Code'), ('business_plan', 'Business plan')], default='text', max_length=24)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Choix multiple'), ('true_false', 'Vrai / Faux'), ('multiple', 'Réponses multiples'), ('open', 'Question ouverte'), ('association', 'Association'), ('ordering', 'Classement')], max_length=16)),
                ('text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct', models.JSONField(blank=True, default=list)),
                ('points', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('quiz_type', models.CharField(choices=[('quiz', 'Quiz'), ('mini_assessment', 'Mini-évaluation'), ('project', 'Projet'), ('final_assessment', 'Évaluation finale')], default='quiz', max_length=24)),
                ('pass_score', models.PositiveSmallIntegerField(default=60, help_text='Score minimum (0-100)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('instructions', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=15)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('checked_ai', 'Corrigée (IA)'), ('validated', 'Validée (humain)')], default='submitted', max_length=24)),
                ('ai_score', models.JSONField(blank=True, default=dict)),
                ('human_validated', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
